// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPlHpgJr3HM-FFmE5tRVVyTNkUzUtsAA',
    appId: '1:537475990111:web:dde63c2195ae063357d1ea',
    messagingSenderId: '537475990111',
    projectId: 'football-coach-app-6003d',
    authDomain: 'football-coach-app-6003d.firebaseapp.com',
    storageBucket: 'football-coach-app-6003d.firebasestorage.app',
    measurementId: 'G-PPBHNJXRVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__Qe2FVBovYhT1PzvpEwadLQOAzAw7Zs',
    appId: '1:537475990111:android:c155c0c14600622757d1ea',
    messagingSenderId: '537475990111',
    projectId: 'football-coach-app-6003d',
    storageBucket: 'football-coach-app-6003d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPk5E2T_3SdxdFQSSollfuFYHj4Ycc5qI',
    appId: '1:537475990111:ios:8e416528d59198a157d1ea',
    messagingSenderId: '537475990111',
    projectId: 'football-coach-app-6003d',
    storageBucket: 'football-coach-app-6003d.firebasestorage.app',
    iosBundleId: 'com.kameer.footballCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPk5E2T_3SdxdFQSSollfuFYHj4Ycc5qI',
    appId: '1:537475990111:ios:8e416528d59198a157d1ea',
    messagingSenderId: '537475990111',
    projectId: 'football-coach-app-6003d',
    storageBucket: 'football-coach-app-6003d.firebasestorage.app',
    iosBundleId: 'com.kameer.footballCoachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEPlHpgJr3HM-FFmE5tRVVyTNkUzUtsAA',
    appId: '1:537475990111:web:25a3d7354b87b10f57d1ea',
    messagingSenderId: '537475990111',
    projectId: 'football-coach-app-6003d',
    authDomain: 'football-coach-app-6003d.firebaseapp.com',
    storageBucket: 'football-coach-app-6003d.firebasestorage.app',
    measurementId: 'G-LTH957C110',
  );
}
